import '@radix-ui/themes/styles.css'
import { Theme } from '@radix-ui/themes'

import { cookies } from 'next/headers'

import { TRPCReactProvider } from '~/trpc/react'
import StyledComponentsRegistry from '~/styles/registry'
import '../styles/theme-config.css'
import { WagmiProvider } from 'wagmi'
import { wagmiConfig } from '~/lib/wagmi-config'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

export const metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const queryClient = new QueryClient()

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body style={{ margin: 0 }}>
				<TRPCReactProvider cookies={cookies().toString()}>
					<WagmiProvider config={wagmiConfig}>
						<QueryClientProvider client={queryClient}>
							<Theme>
								<StyledComponentsRegistry>{children}</StyledComponentsRegistry>
							</Theme>
						</QueryClientProvider>
					</WagmiProvider>
				</TRPCReactProvider>
			</body>
		</html>
	)
}
